"""
Productionizer agent — main orchestration loop.

Each run:
  1. Load state (which service/gap combinations are done)
  2. Pick the next (service, gap) task
  3. Create a git branch in the microservices/ submodule
  4. Run the Gemini 2.0 Flash agentic loop (reads/writes files via tools)
  5. Verify: cargo clippy + cargo test in CI environment
  6. On success: commit, push branch, open a PR
  7. Save updated state

Usage (GitHub Actions sets env vars automatically):
  GOOGLE_API_KEY=...  GH_TOKEN=...  python agents/productionizer/main.py

Optional overrides (for workflow_dispatch manual triggers):
  FORCE_SERVICE=accounts-service  FORCE_GAP=structured-logging
"""

from __future__ import annotations

import datetime
import json
import logging
import os
import pathlib
import subprocess
import sys

from google import genai
from google.genai import protos, types

from prompts import SYSTEM_PROMPT, build_task_prompt
from tasks import build_task_queue, db_name_for_service, pick_next_task
from tools import MICROSERVICES_ROOT, build_tool_declaration, make_dispatch

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
)
log = logging.getLogger("productionizer")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

STATE_FILE = pathlib.Path(__file__).parent / "state.json"
MAX_TOOL_ROUNDS = 25  # safety cap on agent loop iterations


# ---------------------------------------------------------------------------
# State management
# ---------------------------------------------------------------------------

def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {"completed": [], "last_run": None, "last_pr": None}


def save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=2))


# ---------------------------------------------------------------------------
# Git operations (all inside microservices/ submodule)
# ---------------------------------------------------------------------------

def git(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    result = subprocess.run(
        ["git", *args],
        cwd=str(MICROSERVICES_ROOT),
        capture_output=True,
        text=True,
        check=check,
    )
    return result


def branch_name(service: str, gap: str) -> str:
    date = datetime.date.today().strftime("%Y%m%d")
    slug = gap.replace("-", "_")
    return f"productionizer/{date}/{service}/{slug}"


def create_branch(branch: str) -> None:
    log.info("Fetching origin/main in microservices submodule")
    git("fetch", "origin", "main")
    git("checkout", "-b", branch, "origin/main")
    log.info("Created branch: %s", branch)


def commit_changes(service: str, gap: str) -> None:
    git("add", service)
    msg = (
        f"fix({service}): productionizer — {gap}\n\n"
        f"Automated improvement applied by the productionizer agent.\n"
        f"Gap: {gap}\n"
        f"Service: {service}"
    )
    git("commit", "-m", msg)
    log.info("Committed changes for %s / %s", service, gap)


def push_branch(branch: str) -> None:
    git("push", "origin", branch)
    log.info("Pushed branch: %s", branch)


def revert_changes(service: str) -> None:
    """Hard-reset the service directory back to origin/main HEAD and remove untracked files."""
    log.warning("Reverting changes to %s", service)
    git("checkout", "HEAD", "--", service, check=False)
    git("clean", "-fd", service, check=False)


def open_pr(service: str, gap: str, branch: str, summary: str) -> str:
    """Create a PR in rodmen07/microservices via gh CLI. Returns the PR URL."""
    title = f"fix({service}): {gap} — productionizer"
    body = (
        f"## Summary\n\n"
        f"Automated productionizer improvement.\n\n"
        f"- **Service**: `{service}`\n"
        f"- **Gap**: `{gap}`\n"
        f"- **Change**: {summary}\n\n"
        f"## Verification\n\n"
        f"- `cargo clippy` passed (zero new warnings)\n"
        f"- `cargo test` (integration tests) passed\n\n"
        f"> Generated by the productionizer agent — review before merging."
    )
    result = subprocess.run(
        [
            "gh", "pr", "create",
            "--repo", "rodmen07/microservices",
            "--base", "main",
            "--head", branch,
            "--title", title,
            "--body", body,
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


# ---------------------------------------------------------------------------
# Cargo verification
# ---------------------------------------------------------------------------

def run_cargo(service: str, subcommand: str) -> tuple[bool, str]:
    """Run cargo clippy or cargo test for a service. Returns (success, output)."""
    db = db_name_for_service(service)
    database_url = os.environ.get(
        "DATABASE_URL",
        f"postgres://postgres:postgres@localhost:5432/{db}",
    )
    allowed_origins = os.environ.get("ALLOWED_ORIGINS", "http://localhost:5173")

    if subcommand == "clippy":
        cmd = ["cargo", "clippy", "-p", service, "--", "-D", "warnings"]
    elif subcommand == "test":
        cmd = ["cargo", "test", "-p", service, "--test", "integration_test"]
    else:
        raise ValueError(f"Unknown subcommand: {subcommand}")

    env = {
        **os.environ,
        "DATABASE_URL": database_url,
        "ALLOWED_ORIGINS": allowed_origins,
        "AUTH_JWT_SECRET": os.environ.get("AUTH_JWT_SECRET", "dev-insecure-secret-change-me"),
    }

    try:
        result = subprocess.run(
            cmd,
            cwd=str(MICROSERVICES_ROOT),
            capture_output=True,
            text=True,
            timeout=300,
            env=env,
        )
        output = (result.stdout + result.stderr)[:10_000]
        return result.returncode == 0, output
    except subprocess.TimeoutExpired:
        return False, "ERROR: cargo command timed out after 5 minutes"


# ---------------------------------------------------------------------------
# Gemini agentic loop
# ---------------------------------------------------------------------------

def agent_loop(service: str, gap: str) -> str | None:
    """
    Run the Gemini 2.0 Flash tool-call loop.
    Returns the agent's final summary string, or None on failure.
    """
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        log.error("GOOGLE_API_KEY is not set")
        return None

    client = genai.Client(api_key=api_key)
    dispatch = make_dispatch(service)
    tool_declaration = build_tool_declaration()

    chat = client.chats.create(
        model="gemini-2.5-flash",
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            tools=[tool_declaration],
        ),
    )

    user_prompt = build_task_prompt(service, gap)
    log.info("Starting agent loop for %s / %s", service, gap)
    response = chat.send_message(user_prompt)

    summary: str | None = None

    for round_num in range(MAX_TOOL_ROUNDS):
        function_calls = response.function_calls or []

        if not function_calls:
            # No tool calls → model produced a final text response
            summary = getattr(response, "text", None) or ""
            if len(summary.strip()) < 20:
                log.warning("Agent summary too short (%d chars): %r", len(summary), summary)
                summary = None
            else:
                log.info("Agent concluded after %d rounds. Summary: %s", round_num + 1, summary)
            break

        # Execute tool calls and collect results
        result_parts = []
        for fc in function_calls:
            fn_name = fc.name
            fn_args = dict(fc.args) if fc.args else {}
            log.info("Tool call [%d]: %s(%s)", round_num + 1, fn_name, list(fn_args.keys()))

            if fn_name not in dispatch:
                result_text = f"ERROR: unknown tool '{fn_name}'"
            else:
                try:
                    result_text = dispatch[fn_name](fn_args)
                except Exception as exc:
                    result_text = f"ERROR executing {fn_name}: {exc}"

            log.debug("Tool result preview: %.200s", result_text)
            result_parts.append(
                protos.Part(
                    function_response=protos.FunctionResponse(
                        name=fn_name,
                        response={"result": result_text},
                    )
                )
            )

        response = chat.send_message(result_parts)

    else:
        log.error("Agent loop exhausted %d rounds without a final response", MAX_TOOL_ROUNDS)

    return summary


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    state = load_state()

    # Allow manual override via environment variables
    force_service = os.environ.get("FORCE_SERVICE", "").strip()
    force_gap = os.environ.get("FORCE_GAP", "").strip()

    if force_service and force_gap:
        service, gap = force_service, force_gap
        log.info("Using forced task: %s / %s", service, gap)
    else:
        task = pick_next_task(state)
        if task is None:
            log.info("All %d tasks are complete. Nothing to do.", len(build_task_queue()))
            sys.exit(0)
        service, gap = task
        log.info("Selected next task: %s / %s", service, gap)

    branch = branch_name(service, gap)

    # Check if branch already exists on remote (duplicate run guard)
    existing = git("ls-remote", "--heads", "origin", branch, check=False)
    if existing.stdout.strip():
        log.warning("Branch %s already exists on remote — skipping (may be an open PR)", branch)
        sys.exit(0)

    create_branch(branch)

    try:
        # Run the Gemini agent — it reads and writes files in microservices/
        summary = agent_loop(service, gap)
        if not summary:
            log.error("Agent produced no usable summary — reverting")
            revert_changes(service)
            sys.exit(1)

        # Check if the agent actually changed anything
        status = git("status", "--porcelain", service, check=False)
        if not status.stdout.strip():
            log.info("Agent made no file changes (task may already be complete). Exiting cleanly.")
            sys.exit(0)

        # Verify: clippy
        log.info("Running cargo clippy -p %s", service)
        ok, output = run_cargo(service, "clippy")
        if not ok:
            log.error("cargo clippy failed:\n%s", output)
            revert_changes(service)
            sys.exit(1)
        log.info("clippy passed")

        # Verify: integration tests
        log.info("Running cargo test -p %s --test integration_test", service)
        ok, output = run_cargo(service, "test")
        if not ok:
            log.error("cargo test failed:\n%s", output)
            revert_changes(service)
            sys.exit(1)
        log.info("tests passed")

        # Commit, push, open PR
        commit_changes(service, gap)
        push_branch(branch)
        pr_url = open_pr(service, gap, branch, summary)
        log.info("PR opened: %s", pr_url)

        # Persist state
        state.setdefault("completed", []).append([service, gap])
        state["last_run"] = datetime.datetime.utcnow().isoformat() + "Z"
        state["last_pr"] = pr_url
        save_state(state)
        log.info("State saved. Total completed: %d", len(state["completed"]))

    except subprocess.CalledProcessError as exc:
        log.exception("Git or gh command failed: %s\nstderr: %s", exc, exc.stderr)
        revert_changes(service)
        sys.exit(1)
    except Exception as exc:
        log.exception("Unexpected error — reverting: %s", exc)
        revert_changes(service)
        sys.exit(1)


if __name__ == "__main__":
    main()
