"""
Productionizer agent — main orchestration loop — infraportal edition.

Each run:
  1. Load state (which page/gap combinations are done)
  2. Pick the next (page, gap) task
  3. Create a git branch in the infraportal/ clone
  4. Run the Gemini agentic loop (reads/writes files via tools)
  5. Verify: npx tsc --noEmit + npx eslint
  6. On success: commit, push branch, open a PR against rodmen07/infraportal
  7. Save updated state

Usage (GitHub Actions sets env vars automatically):
  GOOGLE_API_KEY=...  GH_TOKEN=...  python agents/productionizer/main.py

Optional overrides (for workflow_dispatch manual triggers):
  FORCE_PAGE=AuditPage  FORCE_GAP=aria-labels
"""

from __future__ import annotations

import datetime
import json
import logging
import os
import pathlib
import subprocess
import sys

from google import genai
from google.genai import errors as genai_errors
from google.genai import types

from prompts import SYSTEM_PROMPT, build_task_prompt
from tasks import build_task_queue, file_path_for_page, pick_next_task
from tools import INFRAPORTAL_ROOT, build_tool_declaration, make_dispatch

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
)
log = logging.getLogger("productionizer")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

STATE_FILE  = pathlib.Path(__file__).parent / "state.json"
OUTPUT_FILE = pathlib.Path(__file__).parent / ".productionizer-output.json"
MAX_TOOL_ROUNDS = 25  # safety cap on agent loop iterations

# Exit codes — read by the workflow loop to decide what to do next.
EXIT_COMMITTED = 0   # task committed; output file written; push + PR needed
EXIT_ERROR     = 1   # unrecoverable error; stop the loop
EXIT_SKIP      = 2   # task skipped (no changes needed); continue to next task
EXIT_DONE      = 3   # all tasks complete; stop the loop


# ---------------------------------------------------------------------------
# State management
# ---------------------------------------------------------------------------

def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {"completed": [], "last_run": None, "last_pr": None}


def save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=2))


# ---------------------------------------------------------------------------
# Git operations (all inside infraportal/ clone)
# ---------------------------------------------------------------------------

def git(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    result = subprocess.run(
        ["git", *args],
        cwd=str(INFRAPORTAL_ROOT),
        capture_output=True,
        text=True,
        check=check,
    )
    return result


def branch_name(page: str, gap: str) -> str:
    date = datetime.date.today().strftime("%Y%m%d")
    slug = gap.replace("-", "_")
    return f"productionizer/{date}/{page}/{slug}"


def create_branch(branch: str) -> None:
    log.info("Fetching origin/main in infraportal clone")
    git("fetch", "origin", "main")
    git("checkout", "-B", branch, "origin/main")
    log.info("Created branch: %s", branch)


def commit_changes(page: str, gap: str) -> None:
    file_path = file_path_for_page(page)
    git("add", file_path)
    msg = (
        f"fix({page}): productionizer — {gap}\n\n"
        f"Automated accessibility improvement applied by the productionizer agent.\n"
        f"Gap: {gap}\n"
        f"Page: {page}"
    )
    git("commit", "-m", msg)
    log.info("Committed changes for %s / %s", page, gap)


def revert_changes(page: str) -> None:
    """Hard-reset the page file back to origin/main HEAD and remove untracked files."""
    log.warning("Reverting changes to %s", page)
    file_path = file_path_for_page(page)
    git("checkout", "HEAD", "--", file_path, check=False)
    git("clean", "-fd", file_path, check=False)


def write_output(branch: str, page: str, gap: str, summary: str) -> None:
    """Write branch + PR metadata for the workflow push/PR step."""
    title = f"fix({page}): {gap} — productionizer"
    body = (
        f"## Summary\n\n"
        f"Automated productionizer accessibility improvement.\n\n"
        f"- **Page**: `{page}`\n"
        f"- **Gap**: `{gap}`\n"
        f"- **Change**: {summary}\n\n"
        f"## Verification\n\n"
        f"- `npx tsc --noEmit` passed (zero type errors)\n"
        f"- `npx eslint src/pages/{page}.tsx --max-warnings=0` passed\n\n"
        f"> Generated by the productionizer agent — review before merging."
    )
    OUTPUT_FILE.write_text(json.dumps({
        "branch": branch,
        "page": page,
        "gap": gap,
        "pr_title": title,
        "pr_body": body,
    }, indent=2))
    log.info("Wrote output to %s (push + PR handled by workflow step)", OUTPUT_FILE)


# ---------------------------------------------------------------------------
# npm/tsc/eslint verification
# ---------------------------------------------------------------------------

def run_npm(page: str, subcommand: str) -> tuple[bool, str]:
    """Run tsc or eslint verification for a page. Returns (success, output)."""
    if subcommand == "tsc":
        cmd = ["npx", "tsc", "--noEmit"]
    elif subcommand == "eslint":
        file_path = file_path_for_page(page)
        cmd = ["npx", "eslint", file_path, "--max-warnings=0"]
    else:
        raise ValueError(f"Unknown subcommand: {subcommand}")

    try:
        result = subprocess.run(
            cmd,
            cwd=str(INFRAPORTAL_ROOT),
            capture_output=True,
            text=True,
            timeout=120,
        )
        output = (result.stdout + result.stderr)[:10_000]
        return result.returncode == 0, output
    except subprocess.TimeoutExpired:
        return False, f"ERROR: {subcommand} timed out after 2 minutes"


# ---------------------------------------------------------------------------
# Gemini agentic loop
# ---------------------------------------------------------------------------

def agent_loop(page: str, gap: str) -> str | None:
    """
    Run the Gemini agentic tool-call loop.
    Returns the agent's final summary string, or None on failure.
    """
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        log.error("GOOGLE_API_KEY is not set")
        return None

    client = genai.Client(api_key=api_key)
    allowed_file = file_path_for_page(page)
    dispatch = make_dispatch(allowed_file)
    tool_declaration = build_tool_declaration()

    chat = client.chats.create(
        model="gemini-2.5-flash",
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            tools=[tool_declaration],
        ),
    )

    user_prompt = build_task_prompt(page, gap)
    log.info("Starting agent loop for %s / %s", page, gap)
    response = chat.send_message(user_prompt)

    summary: str | None = None

    for round_num in range(MAX_TOOL_ROUNDS):
        function_calls = response.function_calls or []

        if not function_calls:
            summary = getattr(response, "text", None) or ""
            if len(summary.strip()) < 20:
                log.warning("Agent summary too short (%d chars): %r", len(summary), summary)
                summary = None
            else:
                log.info("Agent concluded after %d rounds. Summary: %s", round_num + 1, summary)
            break

        result_parts = []
        for fc in function_calls:
            fn_name = fc.name
            fn_args = dict(fc.args) if fc.args else {}
            log.info("Tool call [%d]: %s(%s)", round_num + 1, fn_name, list(fn_args.keys()))

            if fn_name not in dispatch:
                result_text = f"ERROR: unknown tool '{fn_name}'"
            else:
                try:
                    result_text = dispatch[fn_name](fn_args)
                except Exception as exc:
                    result_text = f"ERROR executing {fn_name}: {exc}"

            log.debug("Tool result preview: %.200s", result_text)
            result_parts.append(
                types.Part(
                    function_response=types.FunctionResponse(
                        name=fn_name,
                        response={"result": result_text},
                    )
                )
            )

        response = chat.send_message(result_parts)

    else:
        log.error("Agent loop exhausted %d rounds without a final response", MAX_TOOL_ROUNDS)

    return summary


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    state = load_state()

    force_page = os.environ.get("FORCE_PAGE", "").strip()
    force_gap  = os.environ.get("FORCE_GAP", "").strip()

    if force_page and force_gap:
        page, gap = force_page, force_gap
        log.info("Using forced task: %s / %s", page, gap)
    else:
        task = pick_next_task(state)
        if task is None:
            log.info("All %d tasks are complete. Nothing to do.", len(build_task_queue()))
            sys.exit(EXIT_DONE)
        page, gap = task
        log.info("Selected next task: %s / %s", page, gap)

    branch = branch_name(page, gap)

    # Check if branch already exists on remote (duplicate run guard)
    existing = git("ls-remote", "--heads", "origin", branch, check=False)
    if existing.stdout.strip():
        log.warning("Branch %s already exists on remote — marking done and continuing", branch)
        state.setdefault("completed", []).append([page, gap])
        state["last_run"] = datetime.datetime.now(datetime.UTC).isoformat()
        save_state(state)
        sys.exit(EXIT_SKIP)

    create_branch(branch)

    try:
        summary = agent_loop(page, gap)

        file_path = file_path_for_page(page)
        status = git("status", "--porcelain", file_path, check=False)
        files_changed = bool(status.stdout.strip())

        if not files_changed:
            log.info("Agent made no file changes — marking task done and continuing.")
            state.setdefault("completed", []).append([page, gap])
            state["last_run"] = datetime.datetime.now(datetime.UTC).isoformat()
            save_state(state)
            sys.exit(EXIT_SKIP)

        if summary and summary.upper().startswith("SKIP:"):
            log.info("Agent reported task already satisfied: %s", summary)
            revert_changes(page)
            state.setdefault("completed", []).append([page, gap])
            state["last_run"] = datetime.datetime.now(datetime.UTC).isoformat()
            save_state(state)
            sys.exit(EXIT_SKIP)

        if not summary:
            summary = f"{page}: productionizer applied {gap} improvements"
            log.warning("Agent produced no summary; using fallback: %s", summary)

        # Verify: tsc
        log.info("Running npx tsc --noEmit in infraportal/")
        ok, output = run_npm(page, "tsc")
        if not ok:
            log.error("tsc --noEmit failed:\n%s", output)
            revert_changes(page)
            sys.exit(EXIT_SKIP)
        log.info("tsc passed")

        # Verify: eslint
        log.info("Running npx eslint %s --max-warnings=0", file_path_for_page(page))
        ok, output = run_npm(page, "eslint")
        if not ok:
            log.error("eslint failed:\n%s", output)
            revert_changes(page)
            sys.exit(EXIT_SKIP)
        log.info("eslint passed")

        commit_changes(page, gap)
        write_output(branch, page, gap, summary)

        state.setdefault("completed", []).append([page, gap])
        state["last_run"] = datetime.datetime.now(datetime.UTC).isoformat()
        save_state(state)
        log.info("State saved. Total completed: %d", len(state["completed"]))

    except subprocess.CalledProcessError as exc:
        log.exception("Git or gh command failed: %s\nstderr: %s", exc, exc.stderr)
        revert_changes(page)
        sys.exit(EXIT_ERROR)
    except Exception as exc:
        is_transient = (
            isinstance(exc, genai_errors.ServerError)
            or type(exc).__name__ == "ServerError"
            or (hasattr(exc, "status_code") and getattr(exc, "status_code", 0) >= 500)
        )
        if is_transient:
            log.warning("Transient Gemini API error — reverting and skipping: %s", exc)
            revert_changes(page)
            sys.exit(EXIT_SKIP)
        log.exception("Unexpected error — reverting: %s", exc)
        revert_changes(page)
        sys.exit(EXIT_ERROR)


if __name__ == "__main__":
    main()
