"""
Update the productionizer progress section in the portfolio README.md.
Reads backlog.yaml and rewrites content between
<!-- PRODUCTIONIZER:START --> / <!-- PRODUCTIONIZER:END --> markers.

Usage:
  python agents/productionizer/update_readme.py
"""
from __future__ import annotations

import datetime
import os
import pathlib
import sys

_SCRIPT_DIR = pathlib.Path(__file__).parent
sys.path.insert(0, str(_SCRIPT_DIR))

from tasks import load_backlog, Task  # noqa: E402

MARKER_START = "<!-- PRODUCTIONIZER:START -->"
MARKER_END   = "<!-- PRODUCTIONIZER:END -->"

_WORKSPACE = pathlib.Path(
    os.environ.get("GITHUB_WORKSPACE") or str(_SCRIPT_DIR.parent.parent)
)
README_FILE = _WORKSPACE / "README.md"


def _progress_bar(n: int, total: int, width: int = 30) -> str:
    if total == 0:
        return "░" * width
    filled = int(n / total * width)
    return "█" * filled + "░" * (width - filled)


def _fmt_dt(iso: str | None) -> str:
    if not iso:
        return "never"
    try:
        dt = datetime.datetime.fromisoformat(iso)
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        return str(iso)


def build_progress_section(tasks: list[Task]) -> str:
    total = len(tasks)
    done = sum(1 for t in tasks if t.status == "done")
    skipped = sum(1 for t in tasks if t.status == "skipped")
    pending = sum(1 for t in tasks if t.status == "pending")
    pct = int(done / total * 100) if total else 0
    bar = _progress_bar(done, total)

    # Per-dimension breakdown
    dims: dict[str, dict[str, int]] = {}
    for t in tasks:
        d = dims.setdefault(t.dimension, {"done": 0, "skipped": 0, "pending": 0, "total": 0})
        d["total"] += 1
        if t.status in d:
            d[t.status] += 1

    dim_rows = []
    for dim_id, counts in sorted(dims.items()):
        dim_bar = _progress_bar(counts["done"], counts["total"], width=15)
        dim_rows.append(
            f"| `{dim_id}` | {counts['done']}/{counts['total']} | `{dim_bar}` |"
        )

    dim_table = (
        "| Dimension | Done | Progress |\n"
        "|-----------|------|----------|\n"
        + "\n".join(dim_rows)
    ) if dim_rows else "*(no tasks yet)*"

    # Recent completions
    recent = sorted(
        [t for t in tasks if t.status == "done" and t.summary],
        key=lambda t: t.completed_at or "",
        reverse=True,
    )[:5]
    if recent:
        recent_lines = "\n".join(
            f"- **{t.title}** — {(t.summary or '').split(' — ')[0][:120]}"
            for t in recent
        )
    else:
        recent_lines = "*(none yet)*"

    now = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC")

    return (
        f"{MARKER_START}\n"
        f"## Productionizer Agent\n\n"
        f"Autonomous fullstack developer powered by **Claude Haiku**. "
        f"Picks tasks from a backlog generated by `planner.py`, implements changes across "
        f"any portfolio repo, verifies with language-appropriate tooling, and opens PRs.\n\n"
        f"**Source**: [rodmen07/portfolio — agents/productionizer]"
        f"(https://github.com/rodmen07/portfolio/tree/main/agents/productionizer)\n\n"
        f"---\n\n"
        f"### Overall Progress\n\n"
        f"**{done} / {total} tasks done** ({pct}%) · {skipped} skipped · {pending} pending\n\n"
        f"`{bar}`\n\n"
        f"### By Dimension\n\n"
        f"{dim_table}\n\n"
        f"### Recently Completed\n\n"
        f"{recent_lines}\n\n"
        f"### Stop Conditions\n\n"
        f"Runner pauses when:\n"
        f"- ⚠️ Any target repo has ≥ {15} open PRs awaiting review\n"
        f"- ❌ An unrecoverable error occurs\n"
        f"- ✅ Backlog is empty (run `python planner.py` to generate more)\n\n"
        f"*Last updated: {now} — Do not edit between these markers*\n"
        f"{MARKER_END}"
    )


def main() -> None:
    if not README_FILE.exists():
        print(f"README not found at {README_FILE} — skipping", file=sys.stderr)
        sys.exit(0)

    tasks = load_backlog()
    readme = README_FILE.read_text(encoding="utf-8")
    new_section = build_progress_section(tasks)

    if MARKER_START in readme and MARKER_END in readme:
        start = readme.index(MARKER_START)
        end = readme.index(MARKER_END) + len(MARKER_END)
        new_readme = readme[:start] + new_section + readme[end:]
    else:
        new_readme = readme.rstrip() + "\n\n" + new_section + "\n"

    README_FILE.write_text(new_readme, encoding="utf-8")
    done = sum(1 for t in tasks if t.status == "done")
    total = len(tasks)
    print(f"README updated: {done}/{total} tasks done")


if __name__ == "__main__":
    main()
